[package]
name = "ilya_app"
version = "0.1.0"
edition = "2021"

[dependencies]

# egui
egui = "0.21.0"
egui-wgpu = "0.21.0"
egui-winit = "0.21.1"

# pixels
pixels = "0.12.1"

# winit
winit = "0.28.6"
winit_input_helper = "0.14.1"

ilya = {path = "../ilya"}
